#Le estamos diciendo:

services:
  app-csv:
    build:
      #Construye un servicio
        context: .
          #Desde el contexto donde estás ubicado
        dockerfile: Dockerfile
          #Y encuentra este archivo